### ISSUE TITLE
Object name "%s" is already used' % 

### ISSUE THREAD

**Issue by fermenreq** [STAMP-project/camp#1]
#### Characteristics
- **Issue Type**: feature
- **Reproducibility**: always
- **Severity**: crash
- **Tool/Service/Component**: CityGo, latest version
- **Execution Environment**: [Linux osboxes 4.13.0-41-generic #46~16.04.1-Ubuntu SMP Thu May 3 10:06:43 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux]
- **Reporter**: Fernando Méndez Requena - fernando.mendez@atos.net

#### Description
Can't configure CAMP in oder to run Citygo. I generated the neccesary files following Github readme.

## Composite.yml
```
services:
  db:
    imgfeature: [ubuntu]
  web:
    imgfeature: [python]
  mongo:
    imgfeature: [mongo]
  orion:
    imgfeature: [orion]
  cygnus-common:
    imgfeature [cygnus-common]
  cygnus-ngsi:
    imgfeature [cygnus-ngsi]
constraints:
  - services['web'].alive()
  - varconst(services['db'], 'ThreadPerChild', iv1, varconst(services['db'], 'ThreadLimit', iv2, iv1.value < iv2.value))
outputs:
  big-thread-perchild:
    - varconst(services['db'], 'ThreadPerChild', iv1, iv1.value >= 100)
  small-thread-limit:
    - varconst(services['db'], 'ThreadLimit', iv1, iv1.value <= 64)
```

## features.yml
```
cat features.yml 
ubuntu:
python:
orion:
mongo:
db:
cygnus-common:
cygnus-ngsi:
web:
```

## images.yml
```
downloadimages:
  ubuntu:
    features: [ubuntu]
    name: ubuntu
    tag: latest
  python:
    features: [python]
    name: python
    tag: 2.7
  orion:
    features: [orion]
    name: fiware/orion
    tag: latest
  mongo:
    features: [mongo]
    name: mongo
    tag: 3.2
  cygnus-common:
    features: [cygnus-common]
    name: fiware/cygnus-common
    tag: latest
  cygnus-ngsi:
    features: [cygnus-ngis]
    name: fiware/cygnus-common
    tag: latest

buildingrules:
  db:
    requires: [ubuntu]
    adds: [ubuntu]
    svar: [ThreadLimit, ThreadPerChild]
  mongo:
    adds: [mongo]
  orion:
    adds: [orion]
    depends: [mongo]
  web:
    requires: [python]
    adds: [python]
    depends: [db,orion]
  cygnus-commom:
    adds: [cygnus-common]
  cygnus-ngsi:
    adds: [cygnus-ngsi]

maxfreebuild: 10
constraints:
  - BuildImage.forall(bi1, Not(And(bi1.features.contains(features['db']), bi1.features.contains(features['web']))))

```

## variables.yml

```
ThreadLimit:
  ThreadLimit64:
    type: Int
    value: 64
    operations:
      - substituion1:
          engine: regexp
          filename: "docker-compose.yml"
          placement: "ThreadLimit=64"
          replacement: "ThreadLimit=64"
  ThreadLimit32:
    type: Int
    value: 128 
    operations:
      - substituion1:
          engine: regexp
          filename: "docker-compose.yml"
          placement: "ThreadLimit=64"
          replacement: "ThreadLimit=128"
ThreadPerChild:
  ThreadPerChildFree:
    type: Int
    operations:
      - substituion1:
          engine: regexp
          filename: "docker-compose.yml"
          placement: "ThreadsPerChild=25"
          replacement: "ThreadsPerChild=${value}"
```
## variables.yml~

```
ThreadLimit:
  ThreadLimit64:
    type: Int
    value: 64
    operations:
      - substituion1:
          engine: regexp
          filename: "docker-compose.yml"
          placement: "ThreadLimit=64"
          replacement: "ThreadLimit=64"
  ThreadLimit32:
    type: Int
    value: 32
    operations:
      - substituion1:
          engine: regexp
          filename: "docker-compose.yml"
          placement: "ThreadLimit=64"
          replacement: "ThreadLimit=32"
ThreadPerChild:
  ThreadPerChildFree:
    type: Int
    operations:
      - substituion1:
          engine: regexp
          filename: "docker-compose.yml"
          placement: "ThreadsPerChild=25"
          replacement: "ThreadsPerChild=${value}"
```

#### Output 

```
root@osboxes:/home/osboxes/Proyectos/STAMP/WP2_ATOS_USE_CASE/CAMP/camp-samples/citygo# docker run -it -v $(pwd):/root/workingdir songhui/camp /bin/bash allinone.sh
Working directory is  ./workingdir
Start searching for images
Traceback (most recent call last):
  File "ozepy/stamp/dockerall-var.py", line 474, in <module>
    main(sys.argv[1:])
  File "ozepy/stamp/dockerall-var.py", line 470, in main
    generate(workingdir)
  File "ozepy/stamp/dockerall-var.py", line 310, in generate
    img = DefineObject(name, DownloadImage)
  File "/root/ozepy/src/model.py", line 736, in DefineObject
    _consolas_assert(not (name in _all_objects), 'Object name "%s" is already used' % name)
  File "/root/ozepy/src/model.py", line 18, in _consolas_assert
    raise ConsolasException(msg)
src.model.ConsolasException: Object name "orion" is already used
cp: cannot stat './workingdir/out/ampimages.yml': No such file or directory
cp: cannot stat './workingdir/out/genimages.yml': No such file or directory
cp: cannot stat './workingdir/out/ampcompose.yml': No such file or directory
Input file is  ./workingdir/genimages.yml
Working directory is  ./workingdir
Traceback (most recent call last):
  File "camp/src/dockerfilegen.py", line 87, in <module>
    main(sys.argv[1:])
  File "camp/src/dockerfilegen.py", line 82, in main
    generate(inputfile, workingdir)
  File "camp/src/dockerfilegen.py", line 31, in generate
    with open(file, 'r') as stream:
IOError: [Errno 2] No such file or directory: './workingdir/genimages.yml'
Input file is  ./workingdir/ampcompose.yml
Working directory is  ./workingdir
Traceback (most recent call last):
  File "camp/src/composegen.py", line 216, in <module>
    main(sys.argv[1:])
  File "camp/src/composegen.py", line 211, in main
    generate(seedfile, workingdir, inputfile)
  File "camp/src/composegen.py", line 121, in generate
    with open(amp_result_file, 'r') as stream:
IOError: [Errno 2] No such file or directory: './workingdir/ampcompose.yml'

===========Searching finished.=========
Build all the generated images by: cd <your_dir>/build && bash ./build.sh
Launch one of the configurations by: docker-compose <your_dir>/docker-compose/docker-comopose-<number>.yml up


```
#### Other files and URLs
[docker-compose.yml file](https://gitlab.ow2.org/stamp/atos-uc-city2go/blob/master/Descriptors/Docker/docker-compose.yml)

#### Relationships
[Citygo](https://gitlab.ow2.org/stamp/atos-uc-city2go/blob/master/Descriptors/Docker)

#### [Help on issue template](https://github.com/STAMP-project/camp/blob/master/.github/ISSUE_DOC.md) 
Preview to follow the link or open file .github/ISSUE_DOC.md

**Comment by vassik** [comment]
I have set up an example for CityGo.

Please check out this branch https://github.com/STAMP-project/camp-samples/tree/atos-use-case-morevars

To execute CAMP:
vassik@vassik-vb64:~/GitHub/camp-samples
$ cd ./atos/ && docker run -it -v $(pwd):/root/workingdir vassik/atos-camp:latest /bin/bash allinone.sh

This should generate two configurations with different parameters to for the apache server.
