### ISSUE TITLE
Exception thrown when CAMP model can't be found

### ISSUE THREAD

**Issue by fchauvel** [STAMP-project/camp#25]
#### Characteristics

- **Issue Type**: improvement

- **Reproducibility**: always

- **Severity**: minor

- **Tool/Service/Component**: CAMP v0.2.2

- **Execution Environment**: Debian 9.5

- **Reporter**: Franck Chauvel (on behalf of Assad Montasser)

#### Description

CAMP throws an exception when the CAMP model can't be found. A user-friendly message would be more satisfactory.

#### Steps to reproduce
I pulled the docker image and I had this error:

```console
$ sudo docker run -it -v $(pwd):/camp/workspace fchauvel/camp:latest camp generate -d workspace
[sudo] password for assadm:
Unable to find image 'fchauvel/camp:latest' locally
latest: Pulling from fchauvel/camp
a92a4af0fb9c: Pull complete
e6259e154a86: Pull complete
d5986d2ded11: Pull complete
7af9db4c0f03: Pull complete
0397f5f63bfa: Pull complete
548a851ed8e2: Pull complete
3e38740b726d: Pull complete
Digest: 
sha256:a0f15ca9c1c8b5bdbc2b06f43125055be104528e8f76abcfcfd0ba6e31aa73c6
Status: Downloaded newer image for fchauvel/camp:latest
CAMP v0.2.2 (MIT)
Copyright (C) 2017, 2018 SINTEF Digital

Traceback (most recent call last):
   File "/usr/local/bin/camp", line 9, in <module>
     load_entry_point('camp==0.2.2', 'console_scripts', 'camp')()
   File "/usr/local/lib/python2.7/dist-packages/camp/run.py", line 59, 
in main
     runner.start(argv[1:])
   File "/usr/local/lib/python2.7/dist-packages/camp/run.py", line 36, 
in start
     command.send_to(self._camp)
   File "/usr/local/lib/python2.7/dist-packages/camp/commands.py", line 
126, in send_to
     camp.generate(self)
   File "/usr/local/lib/python2.7/dist-packages/camp/core.py", line 33, 
in generate
     model = self._load_model()
   File "/usr/local/lib/python2.7/dist-packages/camp/core.py", line 47, 
in _load_model
     file_name, model, warnings = self._input.model
   File "/usr/local/lib/python2.7/dist-packages/camp/directories.py", 
line 47, in model
     file_name = self._find_model()
   File "/usr/local/lib/python2.7/dist-packages/camp/directories.py", 
line 59, in _find_model
     raise ValueError("Unable to find the CAMP model")
ValueError: Unable to find the CAMP model
```

#### [Help on issue template](https://github.com/STAMP-project/eclipse-ide/blob/master/.github/ISSUE_DOC.md)
Preview to follow the link or open file .github/ISSUE_DOC.md

**Comment by fchauvel** [comment]
Fixed in CAMP v0.2.3.
