### ISSUE TITLE
Problems on camp execute

### ISSUE THREAD

**Issue by nicolabertazzo** [STAMP-project/camp#31]
#### Characteristics

-   **Issue Type**: bug
-   **Reproducibility**: always
-   **Severity**: block
-   **Tool/Service/Component**: camp execute
-   **Execution Environment**: docker fchauvel/camp:v0.2.3 or fchauvel/camp:dev
-   **Reporter**:  Nicola Bertazzo nicola.bertazzo@eng.it

#### Description
Problem executing camp execute.

#### Steps to reproduce
follow the tutorial at this link:
https://stamp-project.github.io/camp/pages/execute.html

- Clone camp repo (https://stamp-project.github.io/camp/pages/execute.html)
- cd camp/samples/execute
- run this command `docker run -it -v $(pwd):/camp/workspace fchauvel/camp:v0.2.3 camp execute -c simple/config.ini`

the error is:

CAMP v0.2.3 (MIT)
Copyright (C) 2017, 2018 SINTEF Digital

Traceback (most recent call last):
  File "/usr/local/bin/camp", line 9, in <module>
    load_entry_point('camp==0.2.3', 'console_scripts', 'camp')()
  File "/usr/local/lib/python2.7/dist-packages/camp/run.py", line 59, in main
    runner.start(argv[1:])
  File "/usr/local/lib/python2.7/dist-packages/camp/run.py", line 34, in start
    command.send_to(self._camp)
  File "/usr/local/lib/python2.7/dist-packages/camp/commands.py", line 183, in send_to
    camp.execute(self)
TypeError: execute() takes exactly 2 arguments (1 given)

#### [Help on issue template](https://github.com/STAMP-project/eclipse-ide/blob/master/.github/ISSUE_DOC.md)
Preview to follow the link or open file .github/ISSUE_DOC.md

**Comment by fchauvel** [comment]
Thanks for the feedback.

CAMP v0.2.3 includes the original version of the CAMP execute command developed last year. We will release CAMP 0.3 with a rewritten CAMP execute, which not only run the configurations but also collects and aggregates the test reports (for Java/JUnit at first).

As suggest you wait a few days before to proceed: We are now testing and documenting it, and we will release later this week or next week (see branch "new_execute".

**Comment by fchauvel** [comment]
Have you got a chance to try the new version of CAMP execute? Just close the issue if it solved your problem.
