### ISSUE TITLE
Error when running camp execute over greetings example

### ISSUE THREAD

**Issue by mboussaa** [STAMP-project/camp#46]
#### Characteristics

-   **Issue Type**: \[bug]
-   **Reproducibility**: \[always]
-   **Severity**: \[block]
-   **Tool/Service/Component**: \[CAMP, 0.3.4]
-   **Execution Environment**: \[Ubuntu 16.04.6 LTS]
-   **Reporter**: \[Mohamed Boussaa, mohamed.boussaa@activeeon.com]
-   **Docker-compose version**: 
```
root@maas-1:~/docker-flame-graphs/camp-0.3.1/samples/java# docker-compose -version
docker-compose version 1.23.2, build 1110ad01
```
-   **Docker version**: 
```
root@maas-1:~/docker-flame-graphs/camp-0.3.1/samples/java# docker -v
Docker version 18.09.5, build e8ff056
```
#### Description
I hit the following error message when running camp over greetings example:
```
root@maas-1:~/docker-flame-graphs/camp/samples/java# docker run -t -v $PWD:/campworkingdir camp camp execute -d /campworkingdir
CAMP v0.3.4 (MIT)
Copyright (C) 2017 -- 2019 SINTEF Digital

Loaded '/campworkingdir/camp.yaml'.
Loading configurations from '/campworkingdir/out' ...

 - Executing /campworkingdir/out/config_1
   1. Building images ...
      $ bash build_images.sh (from '/campworkingdir/out/config_1/images')
   2. Starting Services ...
      $ docker-compose up -d (from '/campworkingdir/out/config_1')
   5. Stopping Services ...
      $ docker-compose down --volumes --rmi all (from '/campworkingdir/out/config_1')

Test execution aborted!
 - Error: A shell command failed (code: 1)
   $ docker-compose down --volumes --rmi all
   Check out logs in 'camp_execute.log'.

That's all folks!
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/camp/execute/engine.py", line 220, in execute
    self._start_services(each_path)
  File "/usr/local/lib/python3.5/dist-packages/camp/execute/engine.py", line 244, in _start_services
    self._shell.execute(self._START_SERVICES, path)
  File "/usr/local/lib/python3.5/dist-packages/camp/execute/engine.py", line 42, in execute
    result = self._run_shell(command)
  File "/usr/local/lib/python3.5/dist-packages/camp/execute/engine.py", line 66, in _run_shell
    stderr)
camp.execute.engine.ShellCommandFailed: docker-compose up -d (with code 1
Output:
b''

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/camp/core.py", line 139, in execute
    reports = engine.execute(configurations)
  File "/usr/local/lib/python3.5/dist-packages/camp/execute/engine.py", line 231, in execute
    self._stop_services(each_path)
  File "/usr/local/lib/python3.5/dist-packages/camp/execute/engine.py", line 326, in _stop_services
    self._shell.execute(self._STOP_SERVICES, path)
  File "/usr/local/lib/python3.5/dist-packages/camp/execute/engine.py", line 42, in execute
    result = self._run_shell(command)
  File "/usr/local/lib/python3.5/dist-packages/camp/execute/engine.py", line 66, in _run_shell
    stderr)
camp.execute.engine.ShellCommandFailed: docker-compose down --volumes --rmi all (with code 1
Output:
b''

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/camp", line 10, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.5/dist-packages/camp/run.py", line 26, in main
    command.send_to(camp)
  File "/usr/local/lib/python3.5/dist-packages/camp/commands.py", line 185, in send_to
    camp.execute(self)
  File "/usr/local/lib/python3.5/dist-packages/camp/core.py", line 156, in execute
    self._ui.shell_command_failed(error)
  File "/usr/local/lib/python3.5/dist-packages/camp/ui.py", line 145, in shell_command_failed
    self._print(error.output)
  File "/usr/local/lib/python3.5/dist-packages/camp/ui.py", line 221, in _print
    self._output.write(pattern+ "\n")
TypeError: can't concat bytes to str
```
#### Steps to reproduce
-git clone https://github.com/STAMP-project/camp
-docker rmi camp
-docker build . -t camp
-cd samples/java
-docker run -t -v $PWD:/campworkingdir camp camp generate -d /campworkingdir (works fine)
-docker run -t -v $PWD:/campworkingdir camp camp realize -d /campworkingdir (works fine)
-docker run -t -v $PWD:/campworkingdir camp camp execute -d /campworkingdir (error)
#### [Help on issue template](https://github.com/STAMP-project/eclipse-ide/blob/master/.github/ISSUE_DOC.md)
Preview to follow the link or open file .github/ISSUE_DOC.md

**Comment by fchauvel** [comment]
Hi Mohammed,

I got the same error this morning. It's due to some changes I made to run on both python 2.7 and 3.5. I'm testing the fix I wrote. I should be able to release by the end of the day.

I'll keep you posted :-)

**Comment by mboussaa** [comment]
Thanks. I get a different error message with v0.3.5
```
root@maas-1:~/docker-flame-graphs/camp-0.3.5/samples/java# docker run -t -v $PWD:/campworkingdir camp camp realize -d /campworkingdir
CAMP v0.3.5 (MIT)
Copyright (C) 2017 -- 2019 SINTEF Digital

Loaded '/campworkingdir/camp.yaml'.
Loading configurations from '/campworkingdir/out' ...
 - Built configuration '/campworkingdir/out/config_1.
 - Built configuration '/campworkingdir/out/config_2.
 - Built configuration '/campworkingdir/out/config_3.

That's all folks!
root@maas-1:~/docker-flame-graphs/camp-0.3.5/samples/java# docker run -t -v $PWD:/campworkingdir camp camp execute -d /campworkingdir
CAMP v0.3.5 (MIT)
Copyright (C) 2017 -- 2019 SINTEF Digital

Loaded '/campworkingdir/camp.yaml'.
Loading configurations from '/campworkingdir/out' ...

 - Executing /campworkingdir/out/config_1
   1. Building images ...
      $ bash build_images.sh (from '/campworkingdir/out/config_1/images')
   2. Starting Services ...
      $ docker-compose up -d (from '/campworkingdir/out/config_1')
   5. Stopping Services ...
      $ docker-compose down --volumes --rmi all (from '/campworkingdir/out/config_1')

Test execution aborted!
 - Error: A shell command failed (code: 1)
   $ docker-compose down --volumes --rmi all
   Check out logs in 'camp_execute.log'.

Couldn't connect to Docker daemon at http+docker://localhost - is it running?

If it's at a non-standard location, specify the URL with the DOCKER_HOST environment variable.


That's all folks!
```

**Comment by fchauvel** [comment]
Because CAMP execute will spawn docker containers of its own, you share your docker deamon (on the host) with the container where CAMP runs. To do so, just mount it as a volume as follows:

```
$ docker run -v /var/run/docker.sock:/var/run/docker.sock ...
```
Sorry I did not mention about this change of usage. I put an example in the [documentation](https://stamp-project.github.io/camp/pages/setup.html) though. Just let me know if it's unclear.

**Comment by mboussaa** [comment]
Perfect. I tested again with v0.3.5 and it works. God job. You can close the issue.

**Comment by fchauvel** [comment]
Glad it works.
