### ISSUE TITLE
CAMP doesnt work with new vars changed in docker-compose file enviroments var

### ISSUE THREAD

**Issue by fermenreq** [STAMP-project/camp#8]
Dear @vassik, 

The name of some vars in my ```docker-compose.yml``` file are changed,  cause Im working on a different apache module, i.e  ```mpm-event.conf```.

Attached a piece of my ```docker-compose.yml``` file, with the new vars.
```
   environment:
      - StartServers=2
      - MinSpareThreads=25
      - MaxSpareThreads=75
      - ThreadLimit=64
      - ThreadsPerChild=25
      - MaxRequestWorkers=150
      - MaxConnectionsPerChild=0
```

As I see in ```composite.yml``` ,```images.yml``` and ```variables.yml``` , I changed : ```ThreadPerChild``` to ```ThreadsPerChild``` but it gave me an error

## Error
```
Working directory is  ./workingdir
Start searching for images
Traceback (most recent call last):
  File "ozepy/stamp/dockerall-var.py", line 474, in <module>
    main(sys.argv[1:])
  File "ozepy/stamp/dockerall-var.py", line 470, in main
    generate(workingdir)
  File "ozepy/stamp/dockerall-var.py", line 321, in generate
    img.force_value('svar', resolve_variables(value.get('svar', [])))
  File "ozepy/stamp/dockerall-var.py", line 267, in resolve_variables
    return [variables[n] for n in variablenames]
KeyError: 'ThreadsPerChild'
cp: cannot stat './workingdir/out/ampimages.yml': No such file or directory
cp: cannot stat './workingdir/out/genimages.yml': No such file or directory
cp: cannot stat './workingdir/out/ampcompose.yml': No such file or directory
Input file is  ./workingdir/genimages.yml
Working directory is  ./workingdir
Traceback (most recent call last):
  File "camp/src/dockerfilegen.py", line 87, in <module>
    main(sys.argv[1:])
  File "camp/src/dockerfilegen.py", line 82, in main
    generate(inputfile, workingdir)
  File "camp/src/dockerfilegen.py", line 31, in generate
    with open(file, 'r') as stream:
IOError: [Errno 2] No such file or directory: './workingdir/genimages.yml'
Input file is  ./workingdir/ampcompose.yml
Working directory is  ./workingdir
Traceback (most recent call last):
  File "camp/src/composegen.py", line 216, in <module>
    main(sys.argv[1:])
  File "camp/src/composegen.py", line 211, in main
    generate(seedfile, workingdir, inputfile)
  File "camp/src/composegen.py", line 120, in generate
    reference = yaml.load(stream)
  File "/usr/local/lib/python2.7/dist-packages/yaml/__init__.py", line 71, in load
    return loader.get_single_data()
  File "/usr/local/lib/python2.7/dist-packages/yaml/constructor.py", line 37, in get_single_data
    node = self.get_single_node()
  File "/usr/local/lib/python2.7/dist-packages/yaml/composer.py", line 36, in get_single_node
    document = self.compose_document()
  File "/usr/local/lib/python2.7/dist-packages/yaml/composer.py", line 55, in compose_document
    node = self.compose_node(None, None)
  File "/usr/local/lib/python2.7/dist-packages/yaml/composer.py", line 84, in compose_node
    node = self.compose_mapping_node(anchor)
  File "/usr/local/lib/python2.7/dist-packages/yaml/composer.py", line 133, in compose_mapping_node
    item_value = self.compose_node(node, item_key)
  File "/usr/local/lib/python2.7/dist-packages/yaml/composer.py", line 84, in compose_node
    node = self.compose_mapping_node(anchor)
  File "/usr/local/lib/python2.7/dist-packages/yaml/composer.py", line 133, in compose_mapping_node
    item_value = self.compose_node(node, item_key)
  File "/usr/local/lib/python2.7/dist-packages/yaml/composer.py", line 84, in compose_node
    node = self.compose_mapping_node(anchor)
  File "/usr/local/lib/python2.7/dist-packages/yaml/composer.py", line 133, in compose_mapping_node
    item_value = self.compose_node(node, item_key)
  File "/usr/local/lib/python2.7/dist-packages/yaml/composer.py", line 82, in compose_node
    node = self.compose_sequence_node(anchor)
  File "/usr/local/lib/python2.7/dist-packages/yaml/composer.py", line 110, in compose_sequence_node
    while not self.check_event(SequenceEndEvent):
  File "/usr/local/lib/python2.7/dist-packages/yaml/parser.py", line 98, in check_event
    self.current_event = self.state()
  File "/usr/local/lib/python2.7/dist-packages/yaml/parser.py", line 384, in parse_block_sequence_entry
    if not self.check_token(BlockEntryToken, BlockEndToken):
  File "/usr/local/lib/python2.7/dist-packages/yaml/scanner.py", line 116, in check_token
    self.fetch_more_tokens()
  File "/usr/local/lib/python2.7/dist-packages/yaml/scanner.py", line 257, in fetch_more_tokens
    % ch.encode('utf-8'), self.get_mark())
yaml.scanner.ScannerError: while scanning for the next token
found character '\t' that cannot start any token
  in "./workingdir/docker-compose/docker-compose.yml", line 27, column 8

===========Searching finished.=========
Build all the generated images by: cd <your_dir>/build && bash ./build.sh
Launch one of the configurations by: docker-compose <your_dir>/docker-compose/docker-comopose-<number>.yml up
```

Could you please give me details about how to change it ? 

Thanks,
Fernando

**Comment by fermenreq** [comment]
Comment by @vassik :

> 
> Most likely names to the vars in the camp files are not consistent everywhere with your change. There should be the same name everywhere in the camp files. You can grep 'ThreadPerChild' and replace it with 'ThreadsPerChild' everywhere or you can just change 'placement' and 'replacement' in variables.yml without actually changing variable's name.
> 

This issue can be closed. The solution was found.

## Replacing vars:

```/camp/samples/stamp/atos/variables.yml ``` replace for:

```
ThreadsPerChild:
  ThreadPerChildFree:
    type: Int
    operations:
      - substituion1:
          engine: regexp
          filename: "docker-compose.yml"
          placement: "ThreadsPerChild=25"
          replacement: "ThreadsPerChild=${value}"
```
 In ```/camp/samples/stamp/atos/images.yml```:

```svar: [ThreadLimit, ThreadsPerChild]```

In ```/camp/samples/stamp/atos/composite.yml```:

```
services:
  db:
    imgfeature: [postgres]
  web:
    imgfeature: [showcase]
constraints:
  - services['web'].alive()
  - varconst(services['web'], 'ThreadsPerChild', iv1, varconst(services['web'], 'ThreadLimit', iv2, iv1.value < iv2.value))
outputs:
  big-thread-perchild:
    - varconst(services['web'], 'ThreadsPerChild', iv1, iv1.value >= 100)
  small-thread-limit:
    - varconst(services['web'], 'ThreadLimit', iv1, iv1.value <= 64)
```

Thanks
Fernando.
